DROP DATABASE IF EXISTS HoshiLe;
CREATE DATABASE HoshiLe;

USE HoshiLe;

CREATE TABLE Users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    shoppingCart TEXT,
    isAdmin BIT NOT NULL DEFAULT 0
);

CREATE TABLE Products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    brand VARCHAR(255) NOT NULL,
    price DECIMAL(10, 2) NOT NULL,
    imageUrl VARCHAR(255) NOT NULL
);

CREATE TABLE OrderHeads (
    id INT AUTO_INCREMENT PRIMARY KEY,
    userId INT NOT NULL,
    createDate DATETIME NOT NULL,
    FOREIGN KEY (userId) REFERENCES Users (id)
);

CREATE TABLE OrderDetails (
    id INT AUTO_INCREMENT PRIMARY KEY,
    orderId INT NOT NULL,
    productId INT NOT NULL,
    quantity INT NOT NULL,
    FOREIGN KEY (orderId) REFERENCES OrderHeads (id),
    FOREIGN KEY (productId) REFERENCES Products (id)
);
